#workflow name
name: Shell Commands

#trigger event can put multiple [push, pull, pull_request]
on: [push]

# workflow run is made up of one or more jobs. Runs in paralell by default. Key for each job object is name of the job NO Spaces in name
jobs:   #jobs key
  run-shell-command:  #Job is object, key of object is job name, no spaces (_ or - only)
    runs-on: ubuntu-latest  # value is object
    steps:  #array of objects, each object a step
      - name: echo a string
        run: echo "hello world"
      - name: multiline script
        run: |    # The | says running multiple commands 
          node -v
          npm -v 
      - name: python command  #second step, running python commands
        run:  |
          import platform
          print(platform.processor())
        shell: python
  run-windows-command:  # Second job (default runs in paralell with other jobs
    runs-on: windows-latest
    steps:     # Get the current directory location, do it in both powershell and bash
      - name: Directory Powershell  # powershell is default(windows) so don't have to list shell
        run:  Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
